--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Tuvqlu/Your-own-Hive
build-by-default: true
branches:
- main
projects:
  YourOwnHive:
    path: ""
    libs:
    - src: CortexPE/Commando/Commando
      version: ^3.0.0
      branch: PM4
    lint:
      phpstan: false
...
