#config.yml

Enable Plugin: true

#lobby items
Friends: true
Party: true
Locker: true
Minigame Selector: true

#combo

Hive PvP: true
#if false will be regular vanilla pvp

#friends

UI: true
Enabled: true
Friend Limit: true
#there will be a friend limit
Friend Extend with Hive+: true
#there will be more friend slots with hive+ rank
Requests: true
#you can send friend requests
Requests count as slots: true
Friend Req Lasting Time: -1
#-1 for unlimited
Slot Limit: 100
#how many friends you ca have, -1 for unlimited
Slot limit for staff: -1 
#1 for unlimited
Show Avatar in list: true
#will it show their avatar in list
Show Game from list: true
#will it show what game they are in list
Show hub title in list: true
#will it show their hub title in list
New Friend Notifs: true 
#if false they will be in toggles
Join Game from list: true
#can you join your friends game from a list

#texture-pack

Joining HIVE Screen Enabled: true
Joining Screen Text: HIVE
Photos: true

#ui

Old-UI: false
New-UI: true

#parties

UI: true
Invites: true
Invites only from friends: false
YouTube cannot get invite without friend: true
#you can only invite a YouTube Rank if they are in your friends list
Party Slots: 4
#-1 for unlimited 
TP to game with party: true
Can't queue in party: true
TP to custom server with party: false
Party Slots with Hive+: 8
Party Slots with Staff and YT: 12

#end for now
