#config.yml

Enable Plugin: true

#lobby items
Friends: true
Party: true
Locker: true
Minigame Selector: true

#combo

Hive PvP: true
#if false will be regular vanilla pvp

#friends

UI: true
Enabled: true
Friend Limit: true
#there will be a friend limit
Friend Extend with Hive+: true
#there will be more friend slots with hive+ rank
Requests: true
#you can send friend requests
Requests count as slots: true
Friend Req Lasting Time: -1
#-1 for unlimited
Slot Limit: 100
#how many friends you ca have, -1 for unlimited
Slot limit for staff: -1 
#1 for unlimited
Show Avatar in list: true
#will it show their avatar in list
Show Game from list: true
#will it show what game they are in list
Show hub title in list: true
#will it show their hub title in list
New Friend Notifs: true 
#if false they will be in toggles
Join Game from list: true
#can you join your friends game from a list

#texture-pack

Joining HIVE Screen Enabled: true
Joining Screen Text: HIVE
Photos: true

#ui

Old-UI: false
New-UI: true

#parties

UI: true
Invites: true
Invites only from friends: false
YouTube cannot get invite without friend: true
#you can only invite a YouTube Rank if they are in your friends list
Party Slots: 4
#-1 for unlimited 
TP to game with party: true
Can't queue in party: true
TP to custom server with party: false
Party Slots with Hive+: 8
Party Slots with Staff and YT: 12

#locker

UI: true
Hub Titles: enabled
Avatars: enabled
Costumes: enabled
All: false
#all are automatically unlocked
Staff and YT all: true
#staff and YouTube Rank get all unlocked
3D Costumes: true
Minigame Locker button: false

#pets

UI: true
All: false
Staff and YT all: true
Free Rename: true
Unallowed Names:
 - Shit
 - fuck
 - ass
 - Hive
Cubee: true
Endolotl: true
Dragon: true
Rock: true
Pirate Ship: true

#economy
Money: true
Default money: 1000
Pet Price: 10000
Staff and YT get unlimited: true
Money Commands:
 - addmoney
 - givemoney 
 - takemoney
 - setmoney 
 - seemoney
Monetary Symbol: €

#hubtitles
Hub Titles: true

Hub Title Command: /addht

Hub Title Locker Command: /ht

#dora-the-explorer
Dora The Explorer Location: "0, 0, 0"
World: world

#hardcore-parkour
Hardcore Parkour Location: "0, 50, 60"
World: world

#equip
Auto Equip: true

#hub title model
Default: true
#to make your own add to resource pack
#default is a bee

Hub Title Sound Claim: note.pling
Hub Title Particles: rainbow.swirls

...
